export const constants = {
  APP_TITLE: 'The Movie Database',
  SCREEN_DETAIL_TITLE: 'Movie Details',
  CANCEL: 'Cancel',
  CANCEL_PRESSED: 'Cancel Pressed',
  OK: 'OK',
  OK_PRESSED: 'Ok Pressed',
  START_IMG_FILLED:
    'https://raw.githubusercontent.com/AboutReact/sampleresource/master/star_filled.png',
  START_IMG_BORDER:
    'https://raw.githubusercontent.com/AboutReact/sampleresource/master/star_corner.png',
  RATED_SUCCESSFULLY: 'Movie rated successfully',
  RATE_MOVIE: 'Rate the movie',
  RATE: 'Rate',
  RATINGS: 'Ratings',
  CLOSE: 'Close',
  MESSAGE: 'Message',
  RELEASED_ON: 'Released on',
  AS: 'as',
  CAST: 'Cast',
  STREAM_NOW: 'Movies Streaming now',
  MOVIE_TITLE: 'Movie Title',
  AVARAGE_VOTE: 'Avarage Vote',
  RELEASE_DATE: 'Release Date',
  ID: 'Id',
};
